#ifndef __STREAMING_DEVICE_CONTROLLER_LOG_COMPONENT_HPP__
#define __STREAMING_DEVICE_CONTROLLER_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(SDC)

#endif // __STREAMING_DEVICE_CONTROLLER_LOG_COMPONENT_HPP__
