/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Wed May 21 16:04:22 2025


#ifndef CARTESIANCONTROLSERVERROS2_PARAMSPARSER_H
#define CARTESIANCONTROLSERVERROS2_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class CartesianControlServerROS2.
*
* These are the used parameters:
* | Group name | Parameter name | Type   | Units | Default Value                 | Required | Description      | Notes |
* |:----------:|:--------------:|:------:|:-----:|:-----------------------------:|:--------:|:----------------:|:-----:|
* | -          | name           | string | -     | cartesian_control_server_ros2 | 0        | ROS node name    | -     |
* | -          | fkPeriod       | int    | ms    | 20                            | 0        | FK stream period | -     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device CartesianControlServerROS2 --name cartesian_control_server_ros2 --fkPeriod 20
* \endcode
*
* \code{.unparsed}
* yarpdev --device CartesianControlServerROS2
* \endcode
*
*/

class CartesianControlServerROS2_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    CartesianControlServerROS2_ParamsParser();
    ~CartesianControlServerROS2_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"CartesianControlServerROS2"};
    const std::string m_device_name = {"CartesianControlServerROS2"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 1;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    const std::string m_name_defaultValue = {"cartesian_control_server_ros2"};
    const std::string m_fkPeriod_defaultValue = {"20"};

    std::string m_name = {"cartesian_control_server_ros2"};
    int m_fkPeriod = {20};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
};

#endif
