#ifndef __CARTESIAN_CONTROL_SERVER_ROS2_LOG_COMPONENT_HPP__
#define __CARTESIAN_CONTROL_SERVER_ROS2_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(CCS)

#endif // __CARTESIAN_CONTROL_SERVER_ROS2_LOG_COMPONENT_HPP__
