/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Fri Jul 31 21:56:30 2026


#include "CartesianControlClientROS2_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(CartesianControlClientROS2ParamsCOMPONENT, "yarp.device.CartesianControlClientROS2")
}


CartesianControlClientROS2_ParamsParser::CartesianControlClientROS2_ParamsParser()
{
}


std::vector<std::string> CartesianControlClientROS2_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("cartesianLocal");
    params.push_back("cartesianRemote");
    params.push_back("fkStreamTimeoutSecs");
    return params;
}


bool CartesianControlClientROS2_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="cartesianLocal")
    {
        paramValue = m_cartesianLocal;
        return true;
    }
    if (paramName =="cartesianRemote")
    {
        paramValue = m_cartesianRemote;
        return true;
    }
    if (paramName =="fkStreamTimeoutSecs")
    {
        paramValue = std::to_string(m_fkStreamTimeoutSecs);
        return true;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string CartesianControlClientROS2_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      CartesianControlClientROS2_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(CartesianControlClientROS2ParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter cartesianLocal
    {
        if (config.check("cartesianLocal"))
        {
            m_cartesianLocal = config.find("cartesianLocal").asString();
            yCInfo(CartesianControlClientROS2ParamsCOMPONENT) << "Parameter 'cartesianLocal' using value:" << m_cartesianLocal;
        }
        else
        {
            yCInfo(CartesianControlClientROS2ParamsCOMPONENT) << "Parameter 'cartesianLocal' using DEFAULT value:" << m_cartesianLocal;
        }
        prop_check.unput("cartesianLocal");
    }

    //Parser of parameter cartesianRemote
    {
        if (config.check("cartesianRemote"))
        {
            m_cartesianRemote = config.find("cartesianRemote").asString();
            yCInfo(CartesianControlClientROS2ParamsCOMPONENT) << "Parameter 'cartesianRemote' using value:" << m_cartesianRemote;
        }
        else
        {
            yCInfo(CartesianControlClientROS2ParamsCOMPONENT) << "Parameter 'cartesianRemote' using DEFAULT value:" << m_cartesianRemote;
        }
        prop_check.unput("cartesianRemote");
    }

    //Parser of parameter fkStreamTimeoutSecs
    {
        if (config.check("fkStreamTimeoutSecs"))
        {
            m_fkStreamTimeoutSecs = config.find("fkStreamTimeoutSecs").asFloat64();
            yCInfo(CartesianControlClientROS2ParamsCOMPONENT) << "Parameter 'fkStreamTimeoutSecs' using value:" << m_fkStreamTimeoutSecs;
        }
        else
        {
            yCInfo(CartesianControlClientROS2ParamsCOMPONENT) << "Parameter 'fkStreamTimeoutSecs' using DEFAULT value:" << m_fkStreamTimeoutSecs;
        }
        prop_check.unput("fkStreamTimeoutSecs");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(CartesianControlClientROS2ParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(CartesianControlClientROS2ParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      CartesianControlClientROS2_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: CartesianControlClientROS2\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'cartesianLocal': local port\n");
    doc = doc + std::string("'cartesianRemote': remote port\n");
    doc = doc + std::string("'fkStreamTimeoutSecs': FK stream timeout\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device CartesianControlClientROS2 --cartesianLocal /CartesianControlClient --cartesianRemote /CartesianControl --fkStreamTimeoutSecs 0.5\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device CartesianControlClientROS2\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
