/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Fri Jul 31 21:56:30 2026


#ifndef CARTESIANCONTROLCLIENTROS2_PARAMSPARSER_H
#define CARTESIANCONTROLCLIENTROS2_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class CartesianControlClientROS2.
*
* These are the used parameters:
* | Group name | Parameter name      | Type   | Units | Default Value           | Required | Description       | Notes |
* |:----------:|:-------------------:|:------:|:-----:|:-----------------------:|:--------:|:-----------------:|:-----:|
* | -          | cartesianLocal      | string | -     | /CartesianControlClient | 0        | local port        | -     |
* | -          | cartesianRemote     | string | -     | /CartesianControl       | 0        | remote port       | -     |
* | -          | fkStreamTimeoutSecs | double | s     | 0.5                     | 0        | FK stream timeout | -     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device CartesianControlClientROS2 --cartesianLocal /CartesianControlClient --cartesianRemote /CartesianControl --fkStreamTimeoutSecs 0.5
* \endcode
*
* \code{.unparsed}
* yarpdev --device CartesianControlClientROS2
* \endcode
*
*/

class CartesianControlClientROS2_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    CartesianControlClientROS2_ParamsParser();
    ~CartesianControlClientROS2_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"CartesianControlClientROS2"};
    const std::string m_device_name = {"CartesianControlClientROS2"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_cartesianLocal_defaultValue = {"/CartesianControlClient"};
    const std::string m_cartesianRemote_defaultValue = {"/CartesianControl"};
    const std::string m_fkStreamTimeoutSecs_defaultValue = {"0.5"};

    std::string m_cartesianLocal = {"/CartesianControlClient"};
    std::string m_cartesianRemote = {"/CartesianControl"};
    double m_fkStreamTimeoutSecs = {0.5};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
