/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Mon Aug  3 20:21:41 2026


#ifndef CARTESIANCONTROLCLIENTROS2_PARAMSPARSER_H
#define CARTESIANCONTROLCLIENTROS2_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class CartesianControlClientROS2.
*
* These are the used parameters:
* | Group name | Parameter name | Type   | Units | Default Value                 | Required | Description      | Notes |
* |:----------:|:--------------:|:------:|:-----:|:-----------------------------:|:--------:|:----------------:|:-----:|
* | -          | name           | string | -     | cartesian_control_client_ros2 | 1        | local node name  | -     |
* | -          | remote         | string | -     | cartesian_control_server_ros2 | 1        | remote node name | -     |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device CartesianControlClientROS2 --name cartesian_control_client_ros2 --remote cartesian_control_server_ros2
* \endcode
*
* \code{.unparsed}
* yarpdev --device CartesianControlClientROS2 --name cartesian_control_client_ros2 --remote cartesian_control_server_ros2
* \endcode
*
*/

class CartesianControlClientROS2_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    CartesianControlClientROS2_ParamsParser();
    ~CartesianControlClientROS2_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"CartesianControlClientROS2"};
    const std::string m_device_name = {"CartesianControlClientROS2"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_name_defaultValue = {"cartesian_control_client_ros2"};
    const std::string m_remote_defaultValue = {"cartesian_control_server_ros2"};

    std::string m_name = {"cartesian_control_client_ros2"};
    std::string m_remote = {"cartesian_control_server_ros2"};

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
