#ifndef __FT_COMPENSATION_LOG_COMPONENT_HPP__
#define __FT_COMPENSATION_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(FTC)

#endif // __FT_COMPENSATION_LOG_COMPONENT_HPP__
