#ifndef __KEYBOARD_CONTROLLER_LOG_COMPONENT_HPP__
#define __KEYBOARD_CONTROLLER_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(KC)

#endif // __KEYBOARD_CONTROLLER_LOG_COMPONENT_HPP__
