#ifndef __BASIC_CARTESIAN_CONTROL_LOG_COMPONENT_HPP__
#define __BASIC_CARTESIAN_CONTROL_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(BCC)

#endif // __BASIC_CARTESIAN_CONTROL_LOG_COMPONENT_HPP__
