#ifndef __HAAR_DETECTION_CONTROLLER_LOG_COMPONENT_HPP__
#define __HAAR_DETECTION_CONTROLLER_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(HDC)

#endif // __HAAR_DETECTION_CONTROLLER_LOG_COMPONENT_HPP__
