#ifndef __VISUAL_SERVO_CONTROLLER_LOG_COMPONENT_HPP__
#define __VISUAL_SERVO_CONTROLLER_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(VSC)

#endif // __VISUAL_SERVO_CONTROLLER_LOG_COMPONENT_HPP__
