#ifndef __KDL_SOLVER_LOG_COMPONENT_HPP__
#define __KDL_SOLVER_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(KDLS)
YARP_DECLARE_LOG_COMPONENT(KDLS_QUIET)

#endif // __KDL_SOLVER_LOG_COMPONENT_HPP__
