/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Sat Apr 19 00:49:21 2025


#include "KdlTreeSolver_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(KdlTreeSolverParamsCOMPONENT, "yarp.device.KdlTreeSolver")
}


KdlTreeSolver_ParamsParser::KdlTreeSolver_ParamsParser()
{
    //Default value of parametergravity
    {
        m_gravity.clear();
        yarp::os::Value tempVal;
        tempVal.fromString(m_gravity_defaultValue.c_str());
        yarp::os::Bottle* tempBot = tempVal.asList();
        if (tempBot && tempBot->size()!=0)
        {
            for (size_t i=0; i<tempBot->size(); i++)
            {
                m_gravity.push_back(tempBot->get(i).asFloat64());
            }
        }
        else
        {
             yError() <<"parameter 'gravity' is not a properly formatted bottle";
        }
    }

}


std::vector<std::string> KdlTreeSolver_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("kinematics");
    params.push_back("gravity");
    params.push_back("ikPos");
    params.push_back("epsPos");
    params.push_back("maxIterPos");
    params.push_back("vTranslMax");
    params.push_back("vRotMax");
    params.push_back("lambda");
    params.push_back("weightsJS");
    params.push_back("weightsTS");
    params.push_back("mins");
    params.push_back("maxs");
    params.push_back("maxvels");
    return params;
}


bool      KdlTreeSolver_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(KdlTreeSolverParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    std::string config_string = config.toString();
    yarp::os::Property prop_check(config_string.c_str());
    //Parser of parameter kinematics
    {
        if (config.check("kinematics"))
        {
            m_kinematics = config.find("kinematics").asString();
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'kinematics' using value:" << m_kinematics;
        }
        else
        {
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'kinematics' using DEFAULT value:" << m_kinematics;
        }
        prop_check.unput("kinematics");
    }

    //Parser of parameter gravity
    {
        if (config.check("gravity"))
        {
            {
                m_gravity.clear();
                yarp::os::Bottle* tempBot = config.find("gravity").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_gravity.push_back(tempBot->get(i).asFloat64());
                    }
                }
                else
                {
                     yCError(KdlTreeSolverParamsCOMPONENT) <<"parameter 'gravity' is not a properly formatted bottle";
                }
            }
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'gravity' using value:" << m_gravity;
        }
        else
        {
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'gravity' using DEFAULT value:" << m_gravity;
        }
        prop_check.unput("gravity");
    }

    //Parser of parameter ikPos
    {
        if (config.check("ikPos"))
        {
            m_ikPos = config.find("ikPos").asString();
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'ikPos' using value:" << m_ikPos;
        }
        else
        {
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'ikPos' using DEFAULT value:" << m_ikPos;
        }
        prop_check.unput("ikPos");
    }

    //Parser of parameter epsPos
    {
        if (config.check("epsPos"))
        {
            m_epsPos = config.find("epsPos").asFloat64();
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'epsPos' using value:" << m_epsPos;
        }
        else
        {
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'epsPos' using DEFAULT value:" << m_epsPos;
        }
        prop_check.unput("epsPos");
    }

    //Parser of parameter maxIterPos
    {
        if (config.check("maxIterPos"))
        {
            m_maxIterPos = config.find("maxIterPos").asInt64();
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'maxIterPos' using value:" << m_maxIterPos;
        }
        else
        {
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'maxIterPos' using DEFAULT value:" << m_maxIterPos;
        }
        prop_check.unput("maxIterPos");
    }

    //Parser of parameter vTranslMax
    {
        if (config.check("vTranslMax"))
        {
            m_vTranslMax = config.find("vTranslMax").asFloat64();
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'vTranslMax' using value:" << m_vTranslMax;
        }
        else
        {
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'vTranslMax' using DEFAULT value:" << m_vTranslMax;
        }
        prop_check.unput("vTranslMax");
    }

    //Parser of parameter vRotMax
    {
        if (config.check("vRotMax"))
        {
            m_vRotMax = config.find("vRotMax").asFloat64();
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'vRotMax' using value:" << m_vRotMax;
        }
        else
        {
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'vRotMax' using DEFAULT value:" << m_vRotMax;
        }
        prop_check.unput("vRotMax");
    }

    //Parser of parameter lambda
    {
        if (config.check("lambda"))
        {
            m_lambda = config.find("lambda").asFloat64();
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'lambda' using value:" << m_lambda;
        }
        else
        {
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'lambda' using DEFAULT value:" << m_lambda;
        }
        prop_check.unput("lambda");
    }

    //Parser of parameter weightsJS
    {
        if (config.check("weightsJS"))
        {
            {
                m_weightsJS.clear();
                yarp::os::Bottle* tempBot = config.find("weightsJS").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_weightsJS.push_back(tempBot->get(i).asFloat64());
                    }
                }
                else
                {
                     yCError(KdlTreeSolverParamsCOMPONENT) <<"parameter 'weightsJS' is not a properly formatted bottle";
                }
            }
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'weightsJS' using value:" << m_weightsJS;
        }
        else
        {
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'weightsJS' using DEFAULT value:" << m_weightsJS;
        }
        prop_check.unput("weightsJS");
    }

    //Parser of parameter weightsTS
    {
        if (config.check("weightsTS"))
        {
            {
                m_weightsTS.clear();
                yarp::os::Bottle* tempBot = config.find("weightsTS").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_weightsTS.push_back(tempBot->get(i).asFloat64());
                    }
                }
                else
                {
                     yCError(KdlTreeSolverParamsCOMPONENT) <<"parameter 'weightsTS' is not a properly formatted bottle";
                }
            }
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'weightsTS' using value:" << m_weightsTS;
        }
        else
        {
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'weightsTS' using DEFAULT value:" << m_weightsTS;
        }
        prop_check.unput("weightsTS");
    }

    //Parser of parameter mins
    {
        if (config.check("mins"))
        {
            {
                m_mins.clear();
                yarp::os::Bottle* tempBot = config.find("mins").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_mins.push_back(tempBot->get(i).asFloat64());
                    }
                }
                else
                {
                     yCError(KdlTreeSolverParamsCOMPONENT) <<"parameter 'mins' is not a properly formatted bottle";
                }
            }
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'mins' using value:" << m_mins;
        }
        else
        {
            yCError(KdlTreeSolverParamsCOMPONENT) << "Mandatory parameter 'mins' not found!";
            yCError(KdlTreeSolverParamsCOMPONENT) << "Description of the parameter: lower bound joint position limits";
            yCError(KdlTreeSolverParamsCOMPONENT) << "Remember: Units for this parameter are: 'deg'";
            return false;
        }
        prop_check.unput("mins");
    }

    //Parser of parameter maxs
    {
        if (config.check("maxs"))
        {
            {
                m_maxs.clear();
                yarp::os::Bottle* tempBot = config.find("maxs").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_maxs.push_back(tempBot->get(i).asFloat64());
                    }
                }
                else
                {
                     yCError(KdlTreeSolverParamsCOMPONENT) <<"parameter 'maxs' is not a properly formatted bottle";
                }
            }
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'maxs' using value:" << m_maxs;
        }
        else
        {
            yCError(KdlTreeSolverParamsCOMPONENT) << "Mandatory parameter 'maxs' not found!";
            yCError(KdlTreeSolverParamsCOMPONENT) << "Description of the parameter: upper bound joint position limits";
            yCError(KdlTreeSolverParamsCOMPONENT) << "Remember: Units for this parameter are: 'deg'";
            return false;
        }
        prop_check.unput("maxs");
    }

    //Parser of parameter maxvels
    {
        if (config.check("maxvels"))
        {
            {
                m_maxvels.clear();
                yarp::os::Bottle* tempBot = config.find("maxvels").asList();
                if (tempBot)
                {
                    std::string tempBots = tempBot->toString();
                    for (size_t i=0; i<tempBot->size(); i++)
                    {
                        m_maxvels.push_back(tempBot->get(i).asFloat64());
                    }
                }
                else
                {
                     yCError(KdlTreeSolverParamsCOMPONENT) <<"parameter 'maxvels' is not a properly formatted bottle";
                }
            }
            yCInfo(KdlTreeSolverParamsCOMPONENT) << "Parameter 'maxvels' using value:" << m_maxvels;
        }
        else
        {
            yCError(KdlTreeSolverParamsCOMPONENT) << "Mandatory parameter 'maxvels' not found!";
            yCError(KdlTreeSolverParamsCOMPONENT) << "Description of the parameter: joint velocity limits";
            yCError(KdlTreeSolverParamsCOMPONENT) << "Remember: Units for this parameter are: 'deg/s'";
            return false;
        }
        prop_check.unput("maxvels");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(KdlTreeSolverParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(KdlTreeSolverParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      KdlTreeSolver_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: KdlTreeSolver\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'kinematics': path to file with description of robot kinematics\n");
    doc = doc + std::string("'gravity': gravity vector\n");
    doc = doc + std::string("'ikPos': IK position solver algorithm\n");
    doc = doc + std::string("'epsPos': IK position solver precision\n");
    doc = doc + std::string("'maxIterPos': IK position solver max iterations\n");
    doc = doc + std::string("'vTranslMax': maximum translation speed\n");
    doc = doc + std::string("'vRotMax': maximum rotation speed\n");
    doc = doc + std::string("'lambda': lambda parameter for diff IK\n");
    doc = doc + std::string("'weightsJS': joint space weights\n");
    doc = doc + std::string("'weightsTS': task space weights\n");
    doc = doc + std::string("'mins': lower bound joint position limits\n");
    doc = doc + std::string("'maxs': upper bound joint position limits\n");
    doc = doc + std::string("'maxvels': joint velocity limits\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device KdlTreeSolver --kinematics <optional_value> --gravity \" (0.0 0.0 9.81) \" --ikPos nrjl --epsPos 1e-5 --maxIterPos 1000 --vTranslMax 1.0 --vRotMax 50.0 --lambda 0.01 --weightsJS <optional_value> --weightsTS <optional_value> --mins <mandatory_value> --maxs <mandatory_value> --maxvels <mandatory_value>\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device KdlTreeSolver --mins <mandatory_value> --maxs <mandatory_value> --maxvels <mandatory_value>\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
