/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (1.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Wed Apr 16 14:50:07 2025


#include "CartesianControlServer_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(CartesianControlServerParamsCOMPONENT, "yarp.device.CartesianControlServer")
}


CartesianControlServer_ParamsParser::CartesianControlServer_ParamsParser()
{
}


std::vector<std::string> CartesianControlServer_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("name");
    params.push_back("fkPeriod");
    params.push_back("coordRepr");
    params.push_back("angleRepr");
    params.push_back("angularUnits");
    return params;
}


bool      CartesianControlServer_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(CartesianControlServerParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    std::string config_string = config.toString();
    yarp::os::Property prop_check(config_string.c_str());
    //Parser of parameter name
    {
        if (config.check("name"))
        {
            m_name = config.find("name").asString();
            yCInfo(CartesianControlServerParamsCOMPONENT) << "Parameter 'name' using value:" << m_name;
        }
        else
        {
            yCInfo(CartesianControlServerParamsCOMPONENT) << "Parameter 'name' using DEFAULT value:" << m_name;
        }
        prop_check.unput("name");
    }

    //Parser of parameter fkPeriod
    {
        if (config.check("fkPeriod"))
        {
            m_fkPeriod = config.find("fkPeriod").asInt64();
            yCInfo(CartesianControlServerParamsCOMPONENT) << "Parameter 'fkPeriod' using value:" << m_fkPeriod;
        }
        else
        {
            yCInfo(CartesianControlServerParamsCOMPONENT) << "Parameter 'fkPeriod' using DEFAULT value:" << m_fkPeriod;
        }
        prop_check.unput("fkPeriod");
    }

    //Parser of parameter coordRepr
    {
        if (config.check("coordRepr"))
        {
            m_coordRepr = config.find("coordRepr").asString();
            yCInfo(CartesianControlServerParamsCOMPONENT) << "Parameter 'coordRepr' using value:" << m_coordRepr;
        }
        else
        {
            yCInfo(CartesianControlServerParamsCOMPONENT) << "Parameter 'coordRepr' using DEFAULT value:" << m_coordRepr;
        }
        prop_check.unput("coordRepr");
    }

    //Parser of parameter angleRepr
    {
        if (config.check("angleRepr"))
        {
            m_angleRepr = config.find("angleRepr").asString();
            yCInfo(CartesianControlServerParamsCOMPONENT) << "Parameter 'angleRepr' using value:" << m_angleRepr;
        }
        else
        {
            yCInfo(CartesianControlServerParamsCOMPONENT) << "Parameter 'angleRepr' using DEFAULT value:" << m_angleRepr;
        }
        prop_check.unput("angleRepr");
    }

    //Parser of parameter angularUnits
    {
        if (config.check("angularUnits"))
        {
            m_angularUnits = config.find("angularUnits").asString();
            yCInfo(CartesianControlServerParamsCOMPONENT) << "Parameter 'angularUnits' using value:" << m_angularUnits;
        }
        else
        {
            yCInfo(CartesianControlServerParamsCOMPONENT) << "Parameter 'angularUnits' using DEFAULT value:" << m_angularUnits;
        }
        prop_check.unput("angularUnits");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(CartesianControlServerParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(CartesianControlServerParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      CartesianControlServer_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: CartesianControlServer\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'name': local port prefix\n");
    doc = doc + std::string("'fkPeriod': FK stream period\n");
    doc = doc + std::string("'coordRepr': coordinate representation for transform port\n");
    doc = doc + std::string("'angleRepr': angle representation for transform port\n");
    doc = doc + std::string("'angularUnits': angle representation for transform port\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device CartesianControlServer --name /CartesianServer --fkPeriod 20 --coordRepr cartesian --angleRepr axisAngleScaled --angularUnits degrees\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device CartesianControlServer\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
