#ifndef __ASIBOT_SOLVER_LOG_COMPONENT_HPP__
#define __ASIBOT_SOLVER_LOG_COMPONENT_HPP__

#include <yarp/os/LogComponent.h>

YARP_DECLARE_LOG_COMPONENT(ASIBOT)

#endif // __ASIBOT_SOLVER_LOG_COMPONENT_HPP__
