/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Mon Aug  3 20:35:36 2026


#include "CartesianControlClient_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(CartesianControlClientParamsCOMPONENT, "yarp.device.CartesianControlClient")
}


CartesianControlClient_ParamsParser::CartesianControlClient_ParamsParser()
{
}


std::vector<std::string> CartesianControlClient_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("local");
    params.push_back("remote");
    params.push_back("fkStreamTimeoutSecs");
    return params;
}


bool CartesianControlClient_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="local")
    {
        paramValue = m_local;
        return true;
    }
    if (paramName =="remote")
    {
        paramValue = m_remote;
        return true;
    }
    if (paramName =="fkStreamTimeoutSecs")
    {
        paramValue = std::to_string(m_fkStreamTimeoutSecs);
        return true;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string CartesianControlClient_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      CartesianControlClient_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(CartesianControlClientParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter local
    {
        if (config.check("local"))
        {
            m_local = config.find("local").asString();
            yCInfo(CartesianControlClientParamsCOMPONENT) << "Parameter 'local' using value:" << m_local;
        }
        else
        {
            yCInfo(CartesianControlClientParamsCOMPONENT) << "Parameter 'local' using DEFAULT value:" << m_local;
        }
        prop_check.unput("local");
    }

    //Parser of parameter remote
    {
        if (config.check("remote"))
        {
            m_remote = config.find("remote").asString();
            yCInfo(CartesianControlClientParamsCOMPONENT) << "Parameter 'remote' using value:" << m_remote;
        }
        else
        {
            yCInfo(CartesianControlClientParamsCOMPONENT) << "Parameter 'remote' using DEFAULT value:" << m_remote;
        }
        prop_check.unput("remote");
    }

    //Parser of parameter fkStreamTimeoutSecs
    {
        if (config.check("fkStreamTimeoutSecs"))
        {
            m_fkStreamTimeoutSecs = config.find("fkStreamTimeoutSecs").asFloat64();
            yCInfo(CartesianControlClientParamsCOMPONENT) << "Parameter 'fkStreamTimeoutSecs' using value:" << m_fkStreamTimeoutSecs;
        }
        else
        {
            yCInfo(CartesianControlClientParamsCOMPONENT) << "Parameter 'fkStreamTimeoutSecs' using DEFAULT value:" << m_fkStreamTimeoutSecs;
        }
        prop_check.unput("fkStreamTimeoutSecs");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(CartesianControlClientParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(CartesianControlClientParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      CartesianControlClient_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: CartesianControlClient\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'local': local port\n");
    doc = doc + std::string("'remote': remote port\n");
    doc = doc + std::string("'fkStreamTimeoutSecs': FK stream timeout\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device CartesianControlClient --local /CartesianControlClient --remote /CartesianControl --fkStreamTimeoutSecs 0.5\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device CartesianControlClient\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
